/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e674cf03-12a4-4bbc-8929-6ca3cb6a9ffd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_eag3trFCi",
    "aws_user_pools_web_client_id": "74j7b4a5mcnpprni9t420ie594",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3rbe46aokrbi5hmta7bm5v4wre.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
